### ISSUE TITLE
linux compile error

### ISSUE THREAD

**Issue by beleavschi-ladela** [cooler-SAI/CataCore#1]
Hi, can you help me please with compile error

/home/wow/CataCore/src/server/TER-Server-A/Main.cpp:21:19: fatal error: conio.h: No such file or directory
compilation terminated.
make[2]: *** [src/server/TER-Server-A/CMakeFiles/TER-Server-A.dir/Main.cpp.o] Error 1
make[1]: *** [src/server/TER-Server-A/CMakeFiles/TER-Server-A.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by cooler-SAI** [comment]
nope, really need C++ supporter here
