### ISSUE TITLE
Dk Runes Bugged

### ISSUE THREAD

**Issue by LKArthas** [cooler-SAI/CataCore#7]
The DK Runes are bugged, every time you consume a rune (blood, frost, or Unholy) rune starts it's cooldown perfectly, the problem is that the second rune does not start it's cooldown after is used, instead wait for the first one to complete his cooldown before starts on his own (Example: Cast Blood Strike (cost 1 Blood) starts 10 secs cooldown to refill, Cas Blood Strike Again (cost 1 Blood) no cooldown to refill start until the first one is full charged) so with this problem the DK is not very playable, you miss tons of abilities with that problem

**Comment by cooler-SAI** [comment]
we added new core

**Comment by LKArthas** [comment]
i must compile it or the links will be posted on ac-web? because the last time i spent 72 hours downloading the 1 GB of the server ;), i really like that the worldserver folder will be as a separated link, better download 13 MB of the core and around 100 MB of the DB updates than the whole maps vmaps mmaps again ;) Thanks cooler

**Comment by cooler-SAI** [comment]
Compile and extract new maps, mmaps etc... Don't forget add dbc from patch folder to your server

**Comment by LKArthas** [comment]
all right :) , time to fight with my cmake to compile it has been 2 years from now that i can compile my server because cmake, always giving me the openssl error (even when i got it installed, and install the latest version) let's hope that i can compile now, thanks cooler

**Comment by cooler-SAI** [comment]
np, you are welcome for DB fixes here too)))

**Comment by LKArthas** [comment]
again with the cmake problem :/ i think i'm gone crazy here, i guess i need to wait until you compile it and postit on ac-web to test it, and for DB updates don't worry, i have tons of it, the problem is that i'm still perfecting and making it as a trinity like format, at my way i got for example deepholm quest 99 % only 1 quest not working, a daily that i'm lazy to fix it (not autocomplete) twilight highlands at least 118 quest guaranteed working, almost blizzlike Uldum 100 % quest fixed, (not everyone full blizzlike, thats why i only upload when i'm absolutely sure that the fix is at least 98 % blizzlike, now i'm working in western plaguelands quests, i will upload some more fixes soon, Best regards ;)

**Comment by cooler-SAI** [comment]
ok, will post later Repack,we don't need 100% Blizzlike, we need most workable server

**Comment by cooler-SAI** [comment]
@LKArthas , get last Repack here https://yadi.sk/d/RIbU8qRck7Gkc  waiting for your patches)))

**Comment by LKArthas** [comment]
Lol, Thanks cooler, but you murder me with the repack ;), i will take a lot of time for me to download that 1.6 GB, going to add it to queque on IDM now but it will be more easy for a low speed internet as mine to have only the core files, dbc folder and extractors around 60 MB that takes 2-3 hours to download for me :D, respecting the patches i will upload the best SAI that i'v done so far and upload my actual world database for you to test it if you like ;), even now i keep polish the SAI for perfection. Thanks :D

**Comment by LKArthas** [comment]
Hey another question, two friends of mine have experience in C++ scripting and would like to help as well, can i upload the code to you for testing?

**Comment by cooler-SAI** [comment]
yes,make pull request

**Comment by LKArthas** [comment]
today i finish download the server lol

**Comment by LKArthas** [comment]
going to make a fresh start in the quest fixes as soon i import all the characters to the new server :/
