### ISSUE TITLE
Dalaran Cooking Dailys Currency Fix

### ISSUE THREAD

**Issue by LKArthas** [cooler-SAI/CataCore#8]
The Dailys Cooking Quest was giving honor Points Instead Dalaran Cooling Award Currency This fixes the problem ;)

--- Dalaran Cooking Dailys Currency Fix ----
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13100 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13101 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13102 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13103 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13112 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13113 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13114 LIMIT 1;
UPDATE `quest_template` SET `RewardCurrencyId1`=81 WHERE `Id`=13115 LIMIT 1;

**Comment by cooler-SAI** [comment]
will add when I return from Dubai! Thank you
